#! /bin/sh

# keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# wm config

EXTERNAL_MONITOR="HDMI-1"

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor -d 1
    bspc monitor HDMI-1 -d 2 3 4
else
    bspc monitor -d 1 2 3 4
fi

bspc config border_width         3
bspc config focused_border_color $(xrdb -get color10)
bspc config active_border_color  $(xrdb -get color8)
bspc config normal_border_color  $(xrdb -get color8)
bspc config window_gap           8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Slack desktop='^3'
bspc rule -a Deluge-gtk desktop='^4'

# floating apps

FLOATING_APPS=(Alacritty:ncmpcpp Alacritty:scratch Nm-connection-editor Pavucontrol feh)

for app in "${FLOATING_APPS[@]}"
do
    bspc rule -a $app state=floating center=on follow=on
done

bspc rule -a Alacritty:ncmpcpp rectangle=650x310+0+0
bspc rule -a Pavucontrol rectangle=900x420+0+0
bspc rule -a Nm-connection-editor rectangle=400x500+0+0

# launch polybar
$HOME/dots/polybar/launch.sh

# external rules
bspc config external_rules_command "$HOME/.config/bspwm/external-rules.sh"
