# git prompt
if [ -f /usr/lib/bash-git-prompt/gitprompt.sh ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    GIT_PROMPT_THEME=Default_Arch
    source /usr/lib/bash-git-prompt/gitprompt.sh
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.poetry/bin:$PATH

export PYLINTRC="~/dots/python/pylintrc"

alias mybash="vim ~/.bashrc"
alias mybashs="source ~/.bashrc"
alias myi3="vim ~/.i3/config"
alias updt="sudo pacman -Syu"
alias py="python3"
alias python3='python3'
alias gcm="git commit -m"
alias less="bat"
alias dt="cd ~/dots"
alias prj="cd ~/projects"
alias r="ranger"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gp="git push -u origin HEAD"
alias gpl="git pull origin"
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias vim='emacsclient -t'
alias vi='emacsclient -t'
