# git prompt
if [ -f /usr/lib/bash-git-prompt/gitprompt.sh ]; then
    # To only show the git prompt in or under a repository directory
    # GIT_PROMPT_ONLY_IN_REPO=1
    # To use upstream's default theme
    # GIT_PROMPT_THEME=Default
    # To use upstream's default theme, modified by arch maintainer
    GIT_PROMPT_THEME=Default_Arch
    source /usr/lib/bash-git-prompt/gitprompt.sh
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

export PATH=$HOME/.local/bin:$PATH

export PYLINTRC="~/dots/python/pylintrc"

alias mybash="vim ~/.bashrc"
alias mybashs="source ~/.bashrc"
alias myi3="vim ~/.i3/config"
alias updt="sudo pacman -Syyu"
alias py="python3"
alias python3='python3'
alias gcm="git commit -m"
alias less="bat"
alias dt="cd ~/dots"
alias prj="cd ~/projects"
alias r="ranger"
alias gp="gpsup"
alias gpl="ggpull"
alias em="emacs"
alias emt="emacs -nw"
alias doom="~/.emacs.d/bin/doom"

alias jhr="cd ~/projects/jenga-hr-api && source .env"
