export BROWSER=/usr/bin/firefox
export EDITOR="vim"                  # $EDITOR opens in terminal

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.poetry/bin:$PATH

export PYLINTRC="~/dots/python/pylintrc"
export CLOUDSDK_PYTHON=$(which python3)
export PYTHONBREAKPOINT=ipdb.set_trace

alias myi3="nv ~/dots/i3wm/i3"
alias updt="sudo pacman -Syu"
alias py="python3"
alias python3='python3'
alias less="bat"
alias dt="cd ~/dots"
alias pyf="darker -i ."
alias gcm="git commit -m"
alias gcma="git commit --amend -m"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gp="git push -u origin HEAD"
alias gpl="git pull origin"
alias black="darker"
alias nv="nvim"
alias venv="python -m venv venv --system-site-packages"
