export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(
    git
    pip
    python
    vi-mode
)

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_AUTOSUGGEST_USE_ASYNC="true"
source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export BROWSER=/usr/bin/firefox

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.poetry/bin:$PATH
export PATH=$HOME/.deta/bin:$PATH

export PYLINTRC="~/dots/python/pylintrc"

alias myi3="vim ~/dots/i3wm/i3"
alias updt="sudo pacman -Syu"
alias py="python3"
alias python3='python3'
alias less="bat"
alias dt="cd ~/dots"
alias prj="cd ~/projects"
alias r="ranger"
alias pyf="darker -i ."
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias gcm="git commit -m"
alias ga="git add"
alias gs="git status"
alias gd="git diff"
alias gp="git push -u origin HEAD"
alias gpl="git pull origin"
alias x="startx"
